import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CalendarDays, ExternalLink, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Reveal, RevealImage, RevealTitle } from "@/components/site/motion";
import { mediaById } from "@/data/media";
import { phoneHref, site } from "@/data/site";
import { useT } from "@/hooks/use-t";

function BackLink() {
  const t = useT();
  return <Reveal><Link to="/" className="motion-link inline-flex min-h-11 items-center gap-2 text-xs font-semibold uppercase"><ArrowLeft className="size-4" />{t.pages.back}</Link></Reveal>;
}

function ContactBand({ label }: { label: string }) {
  return <section className="bg-primary py-14 text-primary-foreground"><div className="section-shell grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><h2 className="font-display text-4xl sm:text-6xl">{label}</h2><div className="flex flex-wrap gap-3"><Button asChild variant="dark" size="lg"><Link to="/demande-dinformations">{label}<ArrowRight /></Link></Button>{site.phones.map((phone) => <Button key={phone} asChild variant="outline" size="lg"><a href={phoneHref(phone)}><Phone />{phone}</a></Button>)}</div></div></section>;
}

export function ChantPage() {
  const t = useT();
  return <main className="bg-background pb-24">
    <section className="bg-surface-deep pb-20 pt-32 text-hero-foreground lg:pb-28 lg:pt-40"><div className="section-shell"><BackLink /><div className="mt-9 grid gap-10 border-t border-hero-foreground/20 pt-9 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><RevealTitle lines={[t.chantPage.title]} className="text-7xl sm:text-9xl" /><Reveal><p className="text-lg leading-8 text-hero-foreground/85">{t.chantPage.intro}</p><p className="mt-5 leading-7 text-hero-foreground/65">{t.chantPage.languages}</p></Reveal></div></div></section>
    <section className="section-shell py-20 lg:py-28"><Reveal><p className="text-xs font-semibold uppercase text-primary">{t.chantPage.program}</p></Reveal><div className="mt-8 grid gap-px bg-border md:grid-cols-2">{[[t.chantPage.modern,t.chantPage.modernPublic],[t.chantPage.choir,t.chantPage.choirPublic]].map(([name,audience], index) => <Reveal key={name} index={index}><article className="h-full bg-background p-7 sm:p-10"><span className="text-xs text-muted-foreground">0{index + 1}</span><h2 className="font-display mt-12 text-4xl sm:text-5xl">{name}</h2><p className="mt-4 text-muted-foreground">{audience}</p></article></Reveal>)}</div><div className="mt-10 flex flex-wrap gap-3"><Button asChild variant="dark" size="lg"><Link to="/planning">{t.chantPage.planning}<CalendarDays /></Link></Button><Button asChild variant="outline" size="lg"><Link to="/demande-dinformations">{t.chantPage.info}<ArrowRight /></Link></Button></div></section>
  </main>;
}

export function VisualArtsPage() {
  const t = useT();
  const art = mediaById["oeuvres-eleves"];
  const manga = mediaById["atelier-bd"];
  if (!art || !manga) return null;
  return <main className="bg-background pb-24 pt-32 lg:pt-40"><section className="section-shell"><BackLink /><div className="mt-8 grid gap-10 border-t fine-rule pt-8 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><RevealTitle lines={[t.visualArtsPage.title]} className="text-6xl sm:text-8xl lg:text-9xl" /><Reveal><p className="text-lg leading-8">{t.visualArtsPage.intro}</p><p className="mt-5 leading-7 text-muted-foreground">{t.visualArtsPage.detail}</p></Reveal></div></section><section className="section-shell mt-16 grid gap-10 lg:mt-24 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><figure><RevealImage src={art.src} alt={art.alt} className="aspect-[3/4]" imageClassName="object-cover" /><figcaption className="mt-3 text-sm text-muted-foreground">{art.caption}</figcaption></figure><Reveal><p className="text-xs font-semibold uppercase text-primary">{t.visualArtsPage.workshops}</p><div className="mt-5 border-t fine-rule">{t.visualArtsPage.items.map((item, index) => <div key={item.name} className="grid grid-cols-[2.5rem_1fr] border-b fine-rule py-5"><span className="text-xs text-muted-foreground">0{index + 1}</span><div><h2 className="text-lg font-semibold">{item.name}</h2>{item.audience && <p className="mt-1 text-sm text-muted-foreground">{item.audience}</p>}</div></div>)}</div></Reveal></section><section className="mt-20 bg-surface-deep py-20 text-hero-foreground lg:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><RevealImage src={manga.src} alt={manga.alt} className="aspect-[905/1280]" imageClassName="object-contain" /><Reveal><p className="text-xs font-semibold uppercase text-primary">{t.visualArtsPage.mangaTitle}</p><h2 className="font-display mt-5 text-5xl sm:text-7xl">{t.visualArtsPage.mangaTitle}</h2><p className="mt-7 text-lg text-hero-foreground/75">{t.visualArtsPage.mangaText}</p><Button asChild variant="hero" size="lg" className="mt-8"><Link to="/demande-dinformations">{t.visualArtsPage.info}<ArrowRight /></Link></Button></Reveal></div></section></main>;
}

export function CheerPage() {
  const t = useT();
  return <main className="bg-background pb-24"><section className="bg-surface-deep pb-20 pt-32 text-hero-foreground lg:pb-28 lg:pt-40"><div className="section-shell"><BackLink /><p className="mt-10 text-xs font-semibold uppercase text-primary">{t.cheerPage.eyebrow}</p><RevealTitle lines={[t.cheerPage.title]} className="mt-5 text-6xl sm:text-9xl" /><Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-hero-foreground/80">{t.cheerPage.intro}</p></Reveal></div></section><section className="section-shell py-20 lg:py-28"><Reveal><div className="border-l-2 border-primary bg-muted p-7 sm:p-10"><p className="text-xs font-semibold uppercase text-primary">{t.cheerPage.noticeTitle}</p><p className="mt-4 max-w-3xl text-xl leading-8">{t.cheerPage.notice}</p><div className="mt-7 flex flex-wrap gap-3">{site.phones.map((phone) => <Button key={phone} asChild variant="outline" size="lg"><a href={phoneHref(phone)}><Phone />{phone}</a></Button>)}<Button asChild variant="dark" size="lg"><Link to="/demande-dinformations">{t.cheerPage.info}<ArrowRight /></Link></Button></div></div></Reveal></section></main>;
}

export function FitnessPage() {
  const t = useT();
  return <main className="bg-surface-deep text-hero-foreground"><section className="min-h-[78svh] border-b border-hero-foreground/15 pb-20 pt-32 lg:pt-40"><div className="section-shell"><BackLink /><p className="mt-12 text-xs font-semibold uppercase text-primary">{t.fitnessPage.eyebrow}</p><RevealTitle lines={[t.fitnessPage.title, t.fitnessPage.signature]} className="mt-6 max-w-6xl text-6xl sm:text-8xl lg:text-9xl" /><Reveal><p className="mt-8 max-w-2xl text-xl leading-8 text-hero-foreground/70">{t.fitnessPage.intro}</p></Reveal></div></section><section className="section-shell py-20 lg:py-28"><div className="border-t border-hero-foreground/15">{t.fitnessPage.families.map((family, index) => <Reveal key={family.title} index={index}><article className="grid gap-8 border-b border-hero-foreground/15 py-12 lg:grid-cols-[5rem_.8fr_1.2fr]"><span className="text-sm text-primary">0{index + 1}</span><div><h2 className="font-display text-4xl sm:text-6xl">{family.title}</h2><p className="mt-5 max-w-xl leading-8 text-hero-foreground/65">{family.text}</p></div><ul className="grid content-start gap-px bg-hero-foreground/15 sm:grid-cols-2">{family.classes.map((item) => <li key={item} className="bg-surface-deep p-4 text-sm uppercase">{item}</li>)}</ul></article></Reveal>)}</div></section><section className="bg-primary py-16 text-primary-foreground"><div className="section-shell"><p className="max-w-2xl leading-7">{t.fitnessPage.scheduleNotice}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild variant="dark" size="lg"><Link to="/demande-dinformations">{t.fitnessPage.cta}<ArrowRight /></Link></Button>{site.phones.map((phone) => <Button key={phone} asChild variant="outline" size="lg"><a href={phoneHref(phone)}><Phone />{phone}</a></Button>)}</div></div></section></main>;
}

export function BirthdayPage() {
  const t = useT();
  const photos = ["anniversaire-bulles", "anniversaire-assiettes", "anniversaire-tshirt", "anniversaire-creatif", "anniversaire-decoration"].map((id) => mediaById[id]).filter((item) => item !== undefined);
  const lead = photos[0];
  if (!lead) return null;
  return <main className="bg-background pb-24 pt-32 lg:pt-40"><section className="section-shell"><BackLink /><div className="mt-8 grid gap-10 border-t fine-rule pt-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="text-xs font-semibold uppercase text-primary">{t.birthdayPage.eyebrow}</p><RevealTitle lines={[t.birthdayPage.title]} className="mt-5 text-6xl sm:text-9xl" /></div><Reveal><p className="text-lg leading-8 text-muted-foreground">{t.birthdayPage.intro}</p></Reveal></div></section><section className="section-shell mt-16 lg:mt-24"><figure><RevealImage src={lead.src} alt={lead.alt} className="aspect-[3/4] max-h-[52rem]" /><figcaption className="mt-3 text-sm text-muted-foreground">{lead.caption}</figcaption></figure></section><section className="section-shell mt-20"><RevealTitle lines={[t.birthdayPage.gallery]} className="text-5xl sm:text-7xl" /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{photos.slice(1).map((photo,index) => <Reveal key={photo.id} index={index}><figure><img src={photo.src} alt={photo.alt} width={photo.width} height={photo.height} loading="lazy" className="h-auto w-full" /><figcaption className="mt-3 text-sm text-muted-foreground">{photo.caption}</figcaption></figure></Reveal>)}</div></section><div className="mt-20"><ContactBand label={t.birthdayPage.cta} /></div></main>;
}

export function AboutPage() {
  const t = useT();
  const exterior = mediaById["studio-exterieur"];
  const sign = mediaById["enseigne-lumineuse"];
  const registration = mediaById["studio-inscriptions"];
  if (!exterior || !sign || !registration) return null;
  return <main className="bg-background pb-24 pt-32 lg:pt-40"><section className="section-shell"><BackLink /><p className="mt-10 text-xs font-semibold uppercase text-primary">{t.aboutPage.eyebrow}</p><RevealTitle lines={t.aboutPage.titleLines} className="mt-5 max-w-6xl text-5xl sm:text-7xl lg:text-9xl" /><Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-muted-foreground">{t.aboutPage.intro}</p></Reveal></section><section className="section-shell mt-14"><RevealImage src={exterior.src} alt={t.aboutPage.exteriorAlt} className="aspect-[1920/818]" /></section><section className="section-shell py-20 lg:py-28"><div className="grid gap-px bg-border lg:grid-cols-3">{t.aboutPage.sections.map((item,index) => <Reveal key={item.title} index={index}><article className="h-full bg-background p-7 sm:p-9"><span className="text-xs text-primary">0{index + 1}</span><h2 className="font-display mt-10 text-3xl sm:text-4xl">{item.title}</h2><p className="mt-5 leading-7 text-muted-foreground">{item.text}</p></article></Reveal>)}</div></section><section className="bg-muted py-20 lg:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><RevealImage src={sign.src} alt={t.about.imageAlt} className="aspect-[1024/934]" /><Reveal><p className="text-xs font-semibold uppercase text-primary">{t.aboutPage.credibility}</p><div className="mt-6 border-t fine-rule"><p className="border-b fine-rule py-6 text-lg leading-8">{t.aboutPage.rhythmics}</p><p className="border-b fine-rule py-6 text-lg leading-8">{t.aboutPage.piano}</p><div className="border-b fine-rule py-6"><p className="text-2xl font-semibold">{t.aboutPage.rating}</p><a href={site.mapsUrl} target="_blank" rel="noreferrer" className="motion-link mt-3 inline-flex min-h-11 items-center gap-2 text-sm font-semibold uppercase">{t.aboutPage.google}<ExternalLink className="size-4" /></a></div></div></Reveal></div></section><section className="section-shell py-20"><RevealImage src={registration.src} alt={t.aboutPage.registrationAlt} className="aspect-[1920/1084]" /></section></main>;
}